// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getKoworkersMe, getVacancies, getVacanciesById, type Options, postDevSeed, postVacancies } from '../sdk.gen';
import type { GetKoworkersMeData, GetVacanciesByIdData, GetVacanciesData, PostDevSeedData, PostVacanciesData, PostVacanciesResponse } from '../types.gen';

export const postDevSeedMutation = (options?: Partial<Options<PostDevSeedData>>): UseMutationOptions<unknown, DefaultError, Options<PostDevSeedData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostDevSeedData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postDevSeed({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getKoworkersMeQueryKey = (options?: Options<GetKoworkersMeData>) => createQueryKey('getKoworkersMe', options);

/**
 * Получение данных текущего пользователя
 */
export const getKoworkersMeOptions = (options?: Options<GetKoworkersMeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getKoworkersMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getKoworkersMeQueryKey(options)
    });
};

export const getVacanciesQueryKey = (options?: Options<GetVacanciesData>) => createQueryKey('getVacancies', options);

/**
 * Получение списка вакансий с поиском
 */
export const getVacanciesOptions = (options?: Options<GetVacanciesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getVacancies({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getVacanciesQueryKey(options)
    });
};

/**
 * Создание новой вакансии
 */
export const postVacanciesMutation = (options?: Partial<Options<PostVacanciesData>>): UseMutationOptions<PostVacanciesResponse, DefaultError, Options<PostVacanciesData>> => {
    const mutationOptions: UseMutationOptions<PostVacanciesResponse, DefaultError, Options<PostVacanciesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postVacancies({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getVacanciesByIdQueryKey = (options: Options<GetVacanciesByIdData>) => createQueryKey('getVacanciesById', options);

/**
 * Получение конкретной вакансии
 */
export const getVacanciesByIdOptions = (options: Options<GetVacanciesByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getVacanciesById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getVacanciesByIdQueryKey(options)
    });
};
