// <auto-generated />
using System;
using Koworking.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Koworking.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Koworking.Api.Features.Uploads.Upload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash")
                        .UseCollation("C");

                    b.Property<short>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset>("UploadTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_time");

                    b.Property<long>("UploaderId")
                        .HasColumnType("bigint")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_uploads");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_uploads_hash");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("ix_uploads_uploader_id");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("Koworking.Api.Features.Users.Koworker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_id");

                    b.HasKey("Id")
                        .HasName("pk_koworkers");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("ix_koworkers_keycloak_id");

                    b.ToTable("koworkers", (string)null);
                });

            modelBuilder.Entity("Koworking.Api.Features.Vacancies.Vacancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Expectations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expectations");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<NpgsqlTsVector>("TsVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("ts_vector")
                        .HasComputedColumnSql("gen_vacancy_vector(title, array [description, conditions, expectations])", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_vacancies");

                    b.HasIndex("TsVector")
                        .HasDatabaseName("ix_vacancies_ts_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TsVector"), "GIN");

                    b.ToTable("vacancies", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Koworking.Api.Features.Uploads.Upload", b =>
                {
                    b.HasOne("Koworking.Api.Features.Users.Koworker", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uploads_koworkers_uploader_id");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Koworking.Api.Features.Vacancies.Vacancy", b =>
                {
                    b.OwnsOne("Koworking.Api.Features.Vacancies.Paycheck", "Paycheck", b1 =>
                        {
                            b1.Property<long>("VacancyId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("paycheck_amount");

                            b1.Property<short>("Period")
                                .HasColumnType("smallint")
                                .HasColumnName("paycheck_period");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("paycheck_type");

                            b1.HasKey("VacancyId");

                            b1.ToTable("vacancies");

                            b1.WithOwner()
                                .HasForeignKey("VacancyId")
                                .HasConstraintName("fk_vacancies_vacancies_id");
                        });

                    b.Navigation("Paycheck");
                });
#pragma warning restore 612, 618
        }
    }
}
