// <auto-generated />
using System;
using Koworking.Api.Infrastructure.Data.Analytics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Koworking.Api.Infrastructure.Data.Analytics.Migrations
{
    [DbContext(typeof(AnalyticsContext))]
    partial class AnalyticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Koworking.Api.Features.Visits.SiteVisit", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_at");

                    b.Property<string>("UtmCampaign")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmContent")
                        .HasColumnType("String")
                        .HasColumnName("utm_content");

                    b.Property<string>("UtmMedium")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("utm_medium");

                    b.Property<string>("UtmSource")
                        .IsRequired()
                        .HasColumnType("String")
                        .HasColumnName("utm_source");

                    b.Property<string>("UtmTerm")
                        .HasColumnType("String")
                        .HasColumnName("utm_term");

                    b.ToTable("site_visits");

                    b.ToTable("site_visits", tb => tb
                            .HasMergeTreeEngine()
                            .WithOrderBy("created_at"));
                });
#pragma warning restore 612, 618
        }
    }
}
