// <auto-generated />
using Koworking.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Koworking.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Koworking.Api.Features.Vacancies.Vacancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_vacancies");

                    b.ToTable("vacancies", (string)null);
                });

            modelBuilder.Entity("Koworking.Api.Features.Vacancies.Vacancy", b =>
                {
                    b.OwnsOne("Koworking.Api.Features.Vacancies.Paycheck", "Paycheck", b1 =>
                        {
                            b1.Property<long>("VacancyId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("paycheck_amount");

                            b1.Property<short>("Period")
                                .HasColumnType("smallint")
                                .HasColumnName("paycheck_period");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("paycheck_type");

                            b1.HasKey("VacancyId");

                            b1.ToTable("vacancies");

                            b1.WithOwner()
                                .HasForeignKey("VacancyId")
                                .HasConstraintName("fk_vacancies_vacancies_id");
                        });

                    b.Navigation("Paycheck");
                });
#pragma warning restore 612, 618
        }
    }
}
