/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VacanciesIndexRouteImport } from './routes/vacancies/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as VacanciesIdRouteImport } from './routes/vacancies/$id'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiAuthSignoutRouteImport } from './routes/api.auth.signout'
import { Route as ApiAuthSigninRouteImport } from './routes/api.auth.signin'
import { Route as ApiAuthCallbackRouteImport } from './routes/api.auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesIndexRoute = VacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesIdRoute = VacanciesIdRouteImport.update({
  id: '/vacancies/$id',
  path: '/vacancies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninRoute = ApiAuthSigninRouteImport.update({
  id: '/api/auth/signin',
  path: '/api/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/vacancies/$id': typeof VacanciesIdRoute
  '/profile': typeof ProfileIndexRoute
  '/vacancies': typeof VacanciesIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/vacancies/$id': typeof VacanciesIdRoute
  '/profile': typeof ProfileIndexRoute
  '/vacancies': typeof VacanciesIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/vacancies/$id': typeof VacanciesIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/vacancies/': typeof VacanciesIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/vacancies/$id'
    | '/profile'
    | '/vacancies'
    | '/api/auth/callback'
    | '/api/auth/signin'
    | '/api/auth/signout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/vacancies/$id'
    | '/profile'
    | '/vacancies'
    | '/api/auth/callback'
    | '/api/auth/signin'
    | '/api/auth/signout'
  id:
    | '__root__'
    | '/'
    | '/api/$'
    | '/vacancies/$id'
    | '/profile/'
    | '/vacancies/'
    | '/api/auth/callback'
    | '/api/auth/signin'
    | '/api/auth/signout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  VacanciesIdRoute: typeof VacanciesIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  VacanciesIndexRoute: typeof VacanciesIndexRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSigninRoute: typeof ApiAuthSigninRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies/': {
      id: '/vacancies/'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof VacanciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies/$id': {
      id: '/vacancies/$id'
      path: '/vacancies/$id'
      fullPath: '/vacancies/$id'
      preLoaderRoute: typeof VacanciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin': {
      id: '/api/auth/signin'
      path: '/api/auth/signin'
      fullPath: '/api/auth/signin'
      preLoaderRoute: typeof ApiAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  VacanciesIdRoute: VacanciesIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  VacanciesIndexRoute: VacanciesIndexRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSigninRoute: ApiAuthSigninRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
