// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteUploadsByIdData, DeleteUploadsByIdErrors, DeleteUploadsByIdResponses, GetKoworkersMeData, GetKoworkersMeResponses, GetUploadsByIdData, GetUploadsByIdErrors, GetUploadsData, GetUploadsResponses, GetVacanciesByIdData, GetVacanciesByIdErrors, GetVacanciesByIdResponses, GetVacanciesData, GetVacanciesResponses, PatchKoworkersMeData, PatchKoworkersMeResponses, PostDevSeedData, PostDevSeedResponses, PostUploadsData, PostUploadsErrors, PostUploadsMigrateData, PostUploadsMigrateErrors, PostUploadsMigrateResponses, PostUploadsResponses, PostVacanciesData, PostVacanciesResponses, PostVisitsData, PostVisitsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Сидирование БД случайными вакансиями
 */
export const postDevSeed = <ThrowOnError extends boolean = false>(options?: Options<PostDevSeedData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostDevSeedResponses, unknown, ThrowOnError>({
        url: '/dev/seed',
        ...options
    });
};

/**
 * Удаляет загруженный ранее файл
 */
export const deleteUploadsById = <ThrowOnError extends boolean = false>(options: Options<DeleteUploadsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteUploadsByIdResponses, DeleteUploadsByIdErrors, ThrowOnError>({
        url: '/uploads/{Id}',
        ...options
    });
};

/**
 * Загружает файл из хранилища
 */
export const getUploadsById = <ThrowOnError extends boolean = false>(options: Options<GetUploadsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<unknown, GetUploadsByIdErrors, ThrowOnError>({
        url: '/uploads/{Id}',
        ...options
    });
};

/**
 * Поиск ранее загруженных файлов пользователя
 */
export const getUploads = <ThrowOnError extends boolean = false>(options?: Options<GetUploadsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUploadsResponses, unknown, ThrowOnError>({
        url: '/uploads',
        ...options
    });
};

/**
 * Загрузка файла пользователем
 */
export const postUploads = <ThrowOnError extends boolean = false>(options: Options<PostUploadsData, ThrowOnError>) => {
    return (options.client ?? client).post<PostUploadsResponses, PostUploadsErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/uploads',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Загрузка файла из интернета по URL
 */
export const postUploadsMigrate = <ThrowOnError extends boolean = false>(options?: Options<PostUploadsMigrateData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostUploadsMigrateResponses, PostUploadsMigrateErrors, ThrowOnError>({
        url: '/uploads/migrate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Получение данных текущего пользователя
 */
export const getKoworkersMe = <ThrowOnError extends boolean = false>(options?: Options<GetKoworkersMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetKoworkersMeResponses, unknown, ThrowOnError>({
        url: '/koworkers/me',
        ...options
    });
};

/**
 * Обновление текущего пользователя
 */
export const patchKoworkersMe = <ThrowOnError extends boolean = false>(options?: Options<PatchKoworkersMeData, ThrowOnError>) => {
    return (options?.client ?? client).patch<PatchKoworkersMeResponses, unknown, ThrowOnError>({
        url: '/koworkers/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Получение списка вакансий с поиском
 */
export const getVacancies = <ThrowOnError extends boolean = false>(options?: Options<GetVacanciesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetVacanciesResponses, unknown, ThrowOnError>({
        url: '/vacancies',
        ...options
    });
};

/**
 * Создание новой вакансии
 */
export const postVacancies = <ThrowOnError extends boolean = false>(options?: Options<PostVacanciesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostVacanciesResponses, unknown, ThrowOnError>({
        url: '/vacancies',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Получение конкретной вакансии
 */
export const getVacanciesById = <ThrowOnError extends boolean = false>(options: Options<GetVacanciesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetVacanciesByIdResponses, GetVacanciesByIdErrors, ThrowOnError>({
        url: '/vacancies/{Id}',
        ...options
    });
};

/**
 * Отметка о переходе на сайт
 */
export const postVisits = <ThrowOnError extends boolean = false>(options?: Options<PostVisitsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostVisitsResponses, unknown, ThrowOnError>({
        url: '/visits',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};
