// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | (string & {});
};

/**
 * PaginatedResponseOfVacancyModel
 */
export type PaginatedResponseOfVacancyModel = {
    total: number;
    data: Array<VacancyModel>;
};

/**
 * VacancyModel
 */
export type VacancyModel = {
    name: string;
    location: string;
    imageUrl?: string | null;
};

export type GetVacanciesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset (pagination)
         */
        Offset?: number;
        /**
         * Count (pagination)
         */
        Limit?: number;
    };
    url: '/vacancies';
};

export type GetVacanciesResponses = {
    /**
     * OK
     */
    200: PaginatedResponseOfVacancyModel;
};

export type GetVacanciesResponse = GetVacanciesResponses[keyof GetVacanciesResponses];
