// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/' | (string & {});
};

/**
 * CreateVacancyRequest
 */
export type CreateVacancyRequest = {
    title: string;
    location: string;
    text: string;
    imageUrl: string | null;
    paycheck: Paycheck;
};

/**
 * PaginatedResponseOfVacancyModel
 */
export type PaginatedResponseOfVacancyModel = {
    total: number;
    offset: number;
    limit: number;
    data: Array<VacancyModel>;
};

/**
 * Paycheck
 */
export type Paycheck = {
    amount: number;
    period: PaycheckPeriod;
    type: PaycheckType;
} | null;

/**
 * PaycheckPeriod
 */
export type PaycheckPeriod = 'Hourly' | 'Daily' | 'Weekly' | 'Monthly' | 'Yearly';

/**
 * PaycheckType
 */
export type PaycheckType = 'Net' | 'Gross';

/**
 * VacancyModel
 */
export type VacancyModel = {
    id: string;
    createdAt: string;
    updatedAt: string;
    title: string;
    location: string;
    text: string;
    imageUrl: string | null;
    paycheck: Paycheck;
};

export type GetDevSeedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dev/seed';
};

export type GetDevSeedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetVacanciesData = {
    body?: never;
    path?: never;
    query?: {
        Search?: string;
        /**
         * Offset (pagination)
         */
        Offset?: number;
        /**
         * Count (pagination)
         */
        Limit?: number;
    };
    url: '/vacancies';
};

export type GetVacanciesResponses = {
    /**
     * OK
     */
    200: PaginatedResponseOfVacancyModel;
};

export type GetVacanciesResponse = GetVacanciesResponses[keyof GetVacanciesResponses];

export type PostVacanciesData = {
    body?: CreateVacancyRequest;
    path?: never;
    query?: never;
    url: '/vacancies';
};

export type PostVacanciesResponses = {
    /**
     * OK
     */
    200: VacancyModel;
};

export type PostVacanciesResponse = PostVacanciesResponses[keyof PostVacanciesResponses];

export type GetVacanciesByIdData = {
    body?: never;
    path: {
        Id: string;
    };
    query?: never;
    url: '/vacancies/{Id}';
};

export type GetVacanciesByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetVacanciesByIdResponses = {
    /**
     * OK
     */
    200: VacancyModel;
};

export type GetVacanciesByIdResponse = GetVacanciesByIdResponses[keyof GetVacanciesByIdResponses];
