// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * VacancyModel
 */
export const zVacancyModel = z.object({
    name: z.string(),
    location: z.string(),
    imageUrl: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PaginatedResponseOfVacancyModel
 */
export const zPaginatedResponseOfVacancyModel = z.object({
    total: z.int(),
    data: z.array(zVacancyModel)
});

export const zGetVacanciesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        Offset: z.optional(z.int()).default(0),
        Limit: z.optional(z.int()).default(10)
    }))
});

/**
 * OK
 */
export const zGetVacanciesResponse = zPaginatedResponseOfVacancyModel;
