// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * PaycheckPeriod
 */
export const zPaycheckPeriod = z.enum([
    'Hourly',
    'Daily',
    'Weekly',
    'Monthly',
    'Yearly'
]);

/**
 * PaycheckType
 */
export const zPaycheckType = z.enum([
    'Net',
    'Gross'
]);

/**
 * Paycheck
 */
export const zPaycheck = z.union([
    z.object({
        amount: z.int(),
        period: zPaycheckPeriod,
        type: zPaycheckType
    }),
    z.null()
]);

/**
 * CreateVacancyRequest
 */
export const zCreateVacancyRequest = z.object({
    title: z.string(),
    location: z.string(),
    text: z.string(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]),
    paycheck: zPaycheck
});

/**
 * VacancyModel
 */
export const zVacancyModel = z.object({
    id: z.string(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    title: z.string(),
    location: z.string(),
    text: z.string(),
    imageUrl: z.union([
        z.string(),
        z.null()
    ]),
    paycheck: zPaycheck
});

/**
 * PaginatedResponseOfVacancyModel
 */
export const zPaginatedResponseOfVacancyModel = z.object({
    total: z.int(),
    offset: z.int(),
    limit: z.int(),
    data: z.array(zVacancyModel)
});

export const zGetDevSeedData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetVacanciesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        Search: z.optional(z.string()),
        Offset: z.optional(z.int()).default(0),
        Limit: z.optional(z.int()).default(10)
    }))
});

/**
 * OK
 */
export const zGetVacanciesResponse = zPaginatedResponseOfVacancyModel;

export const zPostVacanciesData = z.object({
    body: z.optional(zCreateVacancyRequest),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostVacanciesResponse = zVacancyModel;

export const zGetVacanciesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        Id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetVacanciesByIdResponse = zVacancyModel;
